---
- hosts: ldapserver
  become: yes
  tasks:
  - name: install packages
    yum: 
      name: ipa-server
      state: present
      
- hosts: ldapclient
  become: yes
  tasks:
  - name: install packages
    yum: 
      name: freeipa-client
      state: present    
