---
- hosts: ldapserver
  become: yes
  tasks:
  - name: stop chronyd
    systemd:
      name: chronyd
      enabled: no
      state: stopped
  - name: Set a hostname 
    hostname:
      name: ldapserver.otusldap.test
      use: systemd
  - name: install packages
    yum: 
      name: 
        - ipa-server
        - epel-release
      state: present
      update_cache: true
  - name: update packages
    yum: 
      name: nss*
      state: latest
  - name: Edit /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: |
        192.168.50.10 ldapserver.otusldap.test
        192.168.50.11 ldapclient.otusldap.test
      state: present
  - name: Install pip
    yum:
      name: 
        - python-pip
        - python-setuptools
      state: present
  - name: Install pexpect
    pip:
      name: pexpect
  - name: Init ipa-server 
    expect: 
      command: ipa-server-install -a 12345678 -p 87654321 -n otusldap.test --hostname=ldapserver.otusldap.test --no-host-dns --ip-address=192.168.50.10 -r OTUSLDAP.TEST
      timeout: null
      responses: 
        '.*Do you want to configure integrated DNS .*': "no"
        '.*Continue to configure the system with these .*': "yes" 
  - name: admin login
    expect:
      command: kinit admin
      responses:
        '.*Password for.*': "12345678"
  - name: Add user ldapclient
    expect:
      command: ipa user-add --first=ldap --last=client --cn="Ldap Client" --displayname=ldapclient --initials=L.C. --homedir=/home/ldapclient --shell=ldapclient --user-auth-type=password --password 
      responses:
        '.*User login.*': "ldapclient"
        '.*Password.*': "12345678"
        '.*Enter Password again to.*': "12345678"
        
        
- hosts: ldapclient
  become: yes
  tasks:
  - name: install packages
    yum: 
      name: freeipa-client
      state: present    
      update_cache: true
  - name: Edit /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: |
        192.168.50.10 ldapserver.otusldap.test
        192.168.50.11 ldapclient.otusldap.test
      state: present
  - name: stop chronyd
    systemd:
      name: chronyd
      enabled: no
      state: stopped
  - name: Set a hostname 
    hostname:
      name: ldapclient.otusldap.test
      use: systemd
  - name: Init ipa-client 
    expect:
      command: ipa-client-install --mkhomedir --domain=otusldap.test --server=ldapserver.otusldap.test --realm=OTUSLDAP.TEST --password=12345678
      responses:
        '.*Proceed with fixed values and no DNS.*': "yes"
        '.*Continue to configure the system with these.*': "yes"
        '.*Do you want to download the CA cert.*': "yes"   
