---       
- hosts: ldapclient
  become: yes
  tasks:
  - name: Set a hostname 
    hostname:
      name: ldapclient.otusldap.test
      use: systemd
  - name: install packages
    yum: 
      name: 
        - freeipa-client
        - epel-release
      state: present    
      update_cache: true
  - name: Install pip
    yum:
      name: 
        - python-pip
        - python-setuptools     
  - name: Install pexpect
    pip:
      name: pexpect
  - name: Edit /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: |
        192.168.50.10 ldapserver.otusldap.test
        192.168.50.11 ldapclient.otusldap.test
      state: present
  - name: stop chronyd
    systemd:
      name: chronyd
      enabled: no
      state: stopped
  - name: Init ipa-client 
    expect:
      command: ipa-client-install --mkhomedir --domain=otusldap.test --server=ldapserver.otusldap.test --realm=OTUSLDAP.TEST
      responses:
        '.*Proceed with fixed values and no DNS.*': "yes"
        '.*Continue to configure the system with these.*': "yes"
        '.*User authorized to enroll.*': "admin"   
        '.*Password for.*': "12345678"   
        '.*Do you want to download the CA cert.*': "yes"   
  - name: Init ipa-client 
    expect:
      command: sudo -i -u ldapclient | ssh-keygen -C ldapclient@otusldap.test
      responses:
        '.*Enter passphrase.*': ""
        '.*Enter same passphrase.*': ""    
    
