---       
- hosts: ldapclient
  become: yes
  tasks:
  - name: Set a hostname 
    hostname:
      name: ldapclient.otusldap.test
      use: systemd
  - name: install packages
    yum: 
      name: 
        - freeipa-client
        - epel-release
      state: present    
      update_cache: true
  - name: Install pip
    yum:
      name: 
        - python-pip
        - python-setuptools     
  - name: Install pexpect
    pip:
      name: pexpect
  - name: Edit /etc/hosts
    lineinfile:
      dest: /etc/hosts
      line: |
        192.168.50.10 ldapserver.otusldap.test
        192.168.50.11 ldapclient.otusldap.test
      state: present
  - name: stop chronyd
    systemd:
      name: chronyd
      enabled: no
      state: stopped
  - name: Init ipa-client 
    expect:
      command: ipa-client-install --mkhomedir --domain=otusldap.test --server=ldapserver.otusldap.test --realm=OTUSLDAP.TEST
      responses:
        '.*Proceed with fixed values and no DNS.*': "yes"
        '.*Continue to configure the system with these.*': "yes"
        '.*User authorized to enroll.*': "admin"   
        '.*Password for.*': "12345678"   
        '.*Do you want to download the CA cert.*': "yes"   
  - name: ssh-keygen
    expect:
      command: ssh-keygen -C ldapclient@otusldap.test
      responses:
        '.*Enter passphrase.*': ""
        '.*Enter same passphrase.*': ""   
        '.*Enter file in which to.*': ""  
  - name: kinit ldapclient
    expect:
      command: kinit ldapclient
      responses:
        '.*Password for.*': "12345678"
        '.*Enter new.*': "12345678"        
        '.*Enter it.*': "12345678" 
  - name: copy ssh key     
    copy:
      src: /root/.ssh/
      dest: /home/ldapclient/.ssh/
      owner: ldapclient
      group: ldapclient
      mode: 600
      remote_src: yes
  - name: add ssh key to ldap
    shell: ipa user-mod alice --sshpubkey="$(cat /home/ldapclient/.ssh/id_rsa.pub)"
